# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aa3b290d91ded901b2a54bcc6625500acf13b2ef796053b40d04c23ef13d1d0e3843b04f7a6573fd4b36cb60ffc4aa4c720058d19546333d3f470210a8e20d3

test:
  secret_key_base: 8a23b2abbc4e71326a7f3d1982990de81c343f262db815d2ddf7bc01b44c2020980937dad15f66fc4234cc580ae96765b5a6fb269526ac660ac2dcc3e74d79b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
